{% extends 'layout.phtml' %}

{% block css %}
        <link rel="stylesheet" href="/osomf/www/css/jquery.ui.all.css">
{% endblock %}
{% block content %}
        {% if err %}
            {% for e in err %}
                <h2>{{ e }}</h2>
            {% endfor %}
        {% else %}

<h1>{{ pageTitle }}</h1>

    <form action="" method="post">
    <fieldset>
        <legend>CI Attributes</legend>

        <dl>
            <dt><label>CI Name</label></dt>
            <dd><input type="text" required value="{{ ciName }}"/></dd>
        </dl>

        <dl>
            <dt><label>Asset Description</label></dt>
            <dd><textarea>{{ ciDesc }}</textarea></dd>
        </dl>

        <dl>
            <dt><label>CI Status</label></dt>
            <dd id="statusBox">
                <input id="ciStatus" value="{{ status }}"/>
                <span style="display:none" id="clearStatusBox"><img src="/osomf/www/img/cross.png"/></span>
            </dd>
            <div class="ui-widget" style="margin-top:2em; font-family:Arial">
        </dl>

        <dl>
            <dt><label>CI Type</label></dt>
            <dd>
                <input id="ciType" type="text" value="{{ type }}"/>
                <span style="display:none" id="clearTypeBox"><img src="/osomf/www/img/cross.png"/></span></dd>
            </dd>
            <div class="ui-widget" style="margin-top:2em; font-family:Arial">
        </dl>

        <dl>
            <dt><label>Serial Number</label></dt>
            <dd><input type="text" required value="{{ serial }}"/></dd>
        </dl>

        <dl>
            <dt><label>CI Location</label></dt>
            <dd>
                    <input id="ciLoc" type="text" value="{{ locName }}"/>
                    <span style="display:none" id="clearLocBox"><img src="/osomf/www/img/cross.png"/></span></dd>
            </dd>
            <div class="ui-widget" style="margin-top:2em; font-family:Arial">

        </dl>
        </fieldset>

        <fieldset>
            <legend>CI Associations</legend>
            <dl>
                <dt><label>Asset Owner</label></dt>
                <dd>
                    <select name="ownerType" id="ownerType">
                        <option value="USER">user</option>
                        <option value="GROUP">group</option>
                    </select>
                    <input id="ciOwner" type="text" value=""/>
                    <span style="display:none" id="clearOwnerBox"><img src="/osomf/www/img/cross.png"/></span></dd>
                </dd>
                <div class="ui-widget" style="margin-top:2em; font-family:Arial">
            </dl>
            
            <dl>
                <dt><label>Asset Project</label></dt>
                <dd>
                    <input id="ciProj" type="text" value=""/>
                    <span style="display:none" id="clearProjBox"><img src="/osomf/www/img/cross.png"/></span></dd>
                </dd>
                <div class="ui-widget" style="margin-top:2em; font-family:Arial">
            </dl>

            <dl>
                <dt><label>CI Physical Parent</label></dt>
                <dd>
                    <input id="ciPhy" type="text" value=""/>
                    <span style="display:none" id="clearPhyBox"><img src="/osomf/www/img/cross.png"/></span></dd>
                </dd>
                <div class="ui-widget" style="margin-top:2em; font-family:Arial">
            </dl>

            <dl>
                <dt><label>CI Net Parent</label></dt>
                <dd>
                    <input id="ciNet" type="text" value=""/>
                    <span style="display:none" id="clearNetBox"><img src="/osomf/www/img/cross.png"/></span></dd>
                </dd>
                <div class="ui-widget" style="margin-top:2em; font-family:Arial">
            </dl>
        </fieldset>
        <dl>
            <dt></dt>
            <dd><input type="submit" value="add"/></dd>
        </dl>


    </form>

    {% endif %}
    {% endblock %}


{% block js %}
        <script type="text/javascript" src="/osomf/www/js/jquery.ui.core.min.js"></script>
        <script type="text/javascript" src="/osomf/www/js/jquery.ui.widget.min.js"></script>
        <script type="text/javascript" src="/osomf/www/js/jquery.ui.position.min.js"></script>
        <script type="text/javascript" src="/osomf/www/js/jquery.ui.autocomplete.min.js"></script>
        <script type="text/javascript" src="/osomf/www/js/asset.js"></script>
{% endblock %}