{% extends "layout.phtml" %}

        {% block title %} {{ title }} {% endblock %}
{% block content %}
        <a href="javascript:history.go(-1)">Go Back</a>
<h2 class="pageHeading">{{ title }}</h2>

    <fieldset>
        <legend>user group data</legend>


        <dl>
            <dt><label>Group Name</label></dt>
            <dd>{{ groupName }}</dd>
        </dl>

        <dl>
            <dt><label>Group Desc</label></dt>
            <dd>{{ groupDesc }}</dd>
        </dl>

        <dl>
            <dt><label>phone</label></dt>
            <dd>{{ phone }}</dd>
        </dl>
        
        <dl>
            <dt><label>pager</label></dt>
            <dd>{{ pager }}</dd>
        </dl>

    </fieldset>
    
    <fieldset>
        <legend>Group Members</legend>
        <table class="baseTable">
            <tr>
                <th>User Name</th>
                <th>Full Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Pager</th>
                <th>status</th>
            </tr>
            {% for u in users %}
            <tr>
                <td><a href="/osomf/user/view/{{ u.uid }}">{{ u.uname }}</a></td>
                <td>{{ u.name }}</td>
                <td>{{ u.email }}</td>
                <td>{{ u.phone }}</td>
                <td>{{ u.pager }}</td>
                <td>{{ u.status }}</td>
            </tr>
            {% endfor %}
        </table>


    </fieldset>

{% endblock %}

