<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="author" content="Brad Bonkoski">
    {# Default CSS to be loaded for all #}
    <link rel="stylesheet" href="/osomf/www/css/main.css" />
    {% block css %}
    {% endblock %}

    <title>OSOMF - {% block title %}Default Title{% endblock %}</title>
</head>
<body>
    {% include "navigation.phtml" %}
  <div id="content">{% block content %}Default Content{% endblock %}</div>
  <div id="footer">
    {% include "footer.phtml" %}
  </div>

    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
    <script type="text/javascript" src="/osomf/www/js/jquery.cookies.2.2.0.min.js"></script>
    <script type="text/javascript" src="/osomf/www/js/storage.js"></script>

    {% block js %}
    {% endblock %}

    <script type="text/javascript">
    $(document).ready(function() {
        //alert("Date: "+new Date().getTime());
        checkForLogin();
    });
    </script>

</body>
</html>