{% extends "layout.phtml" %}

        {% block title %} {{ title }} {% endblock %}
{% block content %}
        <a href="javascript:history.go(-1)">Go Back</a>
<h2 class="pageHeading">{{ title }}</h2>

    <fieldset>
        <legend>location data</legend>


        <dl>
            <dt><label>location Name</label></dt>
            <dd>{{ locName }}</dd>
        </dl>

        <dl>
            <dt><label>location Description</label></dt>
            <dd>{{ locDesc }}</dd>
        </dl>
<!--
        <img style="float:right" src="http://maps.google.com/maps/api/staticmap?center=135 Rio Robles E San Jose, CA 95134&zoom=14&size=200x200&maptype=roadmap&sensor=false"/>
-->

</fieldset>
{% endblock %}

