{% extends "layout.phtml" %}

        {% block title %} {{ title }} {% endblock %}
{% block content %}
<h2 class="pageHeading">{{ title }}</h2>

    <fieldset>
        <legend>user data</legend>


        <dl>
            <dt><label>User Name</label></dt>
            <dd>{{ username }}</dd>
        </dl>

        <dl>
            <dt><label>Full Name</label></dt>
            <dd>{{ fullname }}</dd>
        </dl>

        <dl>
            <dt><label>Email</label></dt>
            <dd><a href="mailto:{{ email }}">{{ email }}</a></dd>
        </dl>

        <dl>
            <dt><label>phone</label></dt>
            <dd>{{ phone }}</dd>
        </dl>

        <dl>
            <dt><label>pager</label></dt>
            <dd>{{ pager }}</dd>
        </dl>

</fieldset>

    <fieldset>
    <legend>group membership</legend>
    <ul>Groups<br/>
        {% for gid, group in groups %}
        <a href="#">{{ group.GroupName }} ({{ gid }})</a><br/>
        {% endfor %}
    <ul/>
        </fieldset>

{% endblock %}

