{% extends "layout.phtml" %}

        {% block css %}
        <link rel="stylesheet" href="/osomf/www/css/jquery.ui.all.css">
{% endblock %}
{% block content %}

        <form method="POST" name="frmIncident" action=''>
        <fieldset>
            <legend>incident information</legend>

            <dl>
                <dt><label>title</label></dt>
                <dd><input type="text" required value="{{ incidentTitle }}"/></dd>
            </dl>

            <dl>
                <dt><label>status</label></dt>
                <dd>{{ status }}</dd>
            </dl>

            <dl>
                <dt><label>Severity</label></dt>
                <dd>{{ severity }}</dd>
            </dl>
            <dl>
                <dt><label>Description</label></dt>
                <dd><textarea>{{ desc }}</textarea></dd>
            </dl>

            <dl>
                <dt><label>Impact</label></dt>
                <dd><textarea>{{ impact }}</textarea></dd>
            </dl>

            <dl>
                <dt><label>Revenue Impact</label></dt>
                <dd><textarea>{{ revImpact }}</textarea></dd>
            </dl>
        </fieldset>

    <fieldset class="container">
    <div class="colLeft">
        <fieldset>
            <legend>timeline</legend>
            <dl>
                <dt><label>Detect Time</label></dt>
                <dd><input type="text" value="{{ detectTime }}"/></dd>
            </dl>
            <dl>
                <dt><label>start time</label></dt>
                <dd><input type="text" value="{{ startTime }}"/></dd>
            </dl>
            <dl>
                <dt><label>create time</label></dt>
                <dd>{{ ctime }}</dd>
            </dl>
            <dl>
                <dt><label>last modified</label></dt>
                <dd>{{ mtime }}</dd>
            </dl>
        </fieldset>
    </div>
    <div class="colRight">
        <fieldset>
            <legend>Resolution</legend>
            <dl>
                <dt><label>Resolve Time</label></dt>
                <dd><input type="text" value="{{ resolveTime }}"/></dd>
            </dl>
            <dl>
                <dt><label>Resolve Steps</label></dt>
                <dd><textarea>{{ resolveSteps }}</textarea></dd>
            </dl>
            <dl>
                <dt><label>Responsible Project</label></dt>
                <dd>
                    <input id="respProj" type="text" value="{{ respProjName }}" size=15/>
                    <span style="display:none" id="clearProjBox"><img src="/osomf/www/img/cross.png"/></span>
                </dd>
                    <input type="hidden" name="projId" id="projId" value="{{ proj }}"/>
                
            </dl>
        </fieldset>
    </div>
    </fieldset>

    <input class="btnUpdate" type="submit" name="subIncident" value="update"/>
    </form>

{% endblock %}


    
{% block js %}
        <script type="text/javascript" src="/osomf/www/js/jquery.ui.core.min.js"></script>
        <script type="text/javascript" src="/osomf/www/js/jquery.ui.widget.min.js"></script>
        <script type="text/javascript" src="/osomf/www/js/jquery.ui.position.min.js"></script>
        <script type="text/javascript" src="/osomf/www/js/jquery.ui.autocomplete.min.js"></script>
    <script type="text/javascript" src="/osomf/www/js/incident.js"></script>
{% endblock %}

