{% extends 'layout.phtml' %}

        {% block content %}
        <div id="pageTitle">
   <h1>Current Listing of Ongoing Incidents</h1>
    <a class="editLink" href="/osomf/incident/edit">Add Asset</a>
</div>


    <table class="baseTable" id="incidentHome">
        <tr>
            <th>Incident</th>
            <th>Title</th>
            <th>Status/Severity</th>
            <th>start time</th>
        </tr>
        {% for i in incidents %}
            <tr>
                <td><a href="/osomf/incident/view/{{ i.incidentId }}">{{ i.incidentId }}</a></td>
                <td>{{ i.title }}</td>
                <td>{{ i.status }} / {{ i.severity }}</td>
                <td>{{ i.start_time }}</td>
            </tr>
        {% endfor %}
    </table>
    {% endblock %}