{% extends "layout.phtml" %}

{% block content %}
        <input type="hidden" id="incidentId" value="{{ incidentId }}"/>
    <a href="/osomf/incident/edit/{{ incidentId }}">edit</a>
        <fieldset>
            <legend>incident information</legend>

            <dl>
                <dt><label>title</label></dt>
                <dd>{{ incidentTitle }}</dd>
            </dl>

            <dl>
                <dt><label>status</label></dt>
                <dd>{{ status }}</dd>
            </dl>

            <dl>
                <dt><label>severity</label></dt>
                <dd>{{ severity }}</dd>
            </dl>

            <dl>
                <dt><label>Description</label></dt>
                <dd>{{ desc }}</dd>
            </dl>

            <dl>
                <dt><label>Impact</label></dt>
                <dd>{{ impact }}</dd>
            </dl>

            <dl>
                <dt><label>Revenue Impact</label></dt>
                <dd>{{ revImpact }}</dd>
            </dl>
        </fieldset>

    <fieldset class="container">
    <div class="colLeft">
        <fieldset>
            <legend>timeline</legend>
            <dl>
                <dt><label>Detect Time</label></dt>
                <dd>{{ detectTime }}</dd>
            </dl>
            <dl>
                <dt><label>start time</label></dt>
                <dd>{{ startTime }}</dd>
            </dl>
            <dl>
                <dt><label>create time</label></dt>
                <dd>{{ ctime }}</dd>
            </dl>
            <dl>
                <dt><label>last modified</label></dt>
                <dd>{{ mtime }}</dd>
            </dl>
        </fieldset>
    </div>
    <div class="colRight">
        <fieldset>
            <legend>Resolution</legend>
            <dl>
                <dt><label>Resolve Time</label></dt>
                <dd>{{ resolveTime }}</dd>
            </dl>
            <dl>
                <dt><label>Resolve Steps</label></dt>
                <dd>{{ resolveSteps }}</dd>
            </dl>
            <dl>
                <dt><label>Responsible Project</label></dt>
                <dd><a href="{{ respProjLink }}">{{ respProjName }}</a></dd>
            </dl>
        </fieldset>
    </div>
    </fieldset>

    <fieldset>
        <legend>impacts <a id="impactAddModal" href="#"><img src="/osomf/www/img/add.png"/></a></legend>
        
    </fieldset>

    <fieldset>
        <legend>Worklog <a id="worklogAddModal" href="#"><img src="/osomf/www/img/add.png"/></a></legend>
        <table class="baseTable" id="incidentWorklogTable">
            <tr>
                <th>user</th>
                <th>time</th>
                <th>type</th>
                <th>data</th>
            </tr>
            {% for wl in worklogs %}
            <tr>
                <td>{{ wl.user }}</td>
                <td>{{ wl.mtime }}</td>
                <td>{{ wl.type }}</td>
                {% if wl.type == 'STATUS' %}
                    <td>[orig] {{ wl.data[0] }} [new] {{ wl.data[1] }} [Reason] {{ wl.data[2] }}</td>
                {% else %}
                <td>{{ wl.data }}</td>
                {% endif %}
            </tr>
            {% endfor %}
        </table>
    </fieldset>

     {% include 'modals/incidentImpact.phtml' %}
     {% include 'modals/incidentWorklog.phtml' %}
{% endblock %}


    
{% block js %}
    <script type="text/javascript" src="/osomf/www/js/jquery.simplemodal.1.4.1.min.js"></script>
    <script type="text/javascript" src="/osomf/www/js/incident.js"></script>
{% endblock %}

